server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  thymeleaf:
    cache: false
  messages:
    basename: messages
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/HospitalBooking?useSSL=false&serverTimezone=UTC
    username: root
    password: Myp@ssword
  jpa:
    open-in-view: false
    hibernate:
      #      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
storage:
  location: uploads
  max-file-size: 10MB
  allowed-extensions: png, jpg, jpeg, bmp
jwt:
  secret-key: ${JWT_SECRET}
  access-expiration: 7200000
  refresh-expiration: 1209600000
  confirm-expiration: 900000
  